name: slack-notification

inputs:
  status:
    required: false
    default: "failure"
  slack_incoming_url:
    required: true
  github_token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch the most recent tag
      id: get_latest_tag
      shell: bash
      run: |
        echo "Fetching the most recent tag..."
        LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "Latest tag: ${LATEST_TAG}"
        echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV

    - name: Send slack
      shell: bash
      env:
        LATEST_TAG: ${{ steps.get_latest_tag.outputs.LATEST_TAG }}
      run: |
        echo "Running Slack notification script..."
        echo "GITHUB_REF: ${GITHUB_REF}"
        echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
        echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"

        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "Detected tag push: ${TAG_NAME}"
          # 태그가 main 브랜치와 연관되어 있는지 확인
          BASE_BRANCH=$(git branch -r --contains "tags/${TAG_NAME}" | grep "origin/main" | wc -l)
          if [[ $BASE_BRANCH -gt 0 ]]; then
            EMOTICON="🚀"
            MSG="{ \"text\":\"${EMOTICON} Tag \`${TAG_NAME}\` related to \`main\` branch has been pushed by \`${GITHUB_ACTOR}\`. <https://github.com/SENSE-IM/sense-turbo/releases|View Release Notes>\" }"
          else
            EMOTICON="✅"
            MSG="{ \"text\":\"${EMOTICON} Tag \`${TAG_NAME}\` has been pushed. <https://github.com/SENSE-IM/sense-turbo/releases|View Release Notes>\" }"
          fi
        elif [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
          if [[ "${{ inputs.status }}" == "success" ]]; then
            echo "Detected dev branch push with success status"
            PR_RESPONSE=$(curl -s -H "Authorization: token ${{ inputs.github_token }}" \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls?state=closed&base=dev&sort=updated&direction=desc" | head -n 1)
            PR_TITLE=$(echo "$PR_RESPONSE" | grep -oP '(?<="title":")[^"]*')
            PR_URL=$(echo "$PR_RESPONSE" | grep -oP '(?<="html_url":")[^"]*')
            EMOTICON="🎉"
            MSG="{ \"text\":\"${EMOTICON} \`dev\` branch has been successfully pushed. [${PR_TITLE}](${PR_URL}) - \`${GITHUB_ACTOR}\`\" }"
          else
            echo "Detected dev branch push with failure status"
            EMOTICON="⛔"
            MSG="{ \"text\":\"${EMOTICON} Deployment failed for \`dev\` branch pushed by \`${GITHUB_ACTOR}\`.\" }"
          fi
        else
          echo "Deployment failed for an unknown reason"
          EMOTICON="⛔"
          MSG="{ \"text\":\"${EMOTICON} Deployment failed for \`${GITHUB_REF}\` branch pushed by \`${GITHUB_ACTOR}\`.\" }"
        fi

        echo "Sending message to Slack: $MSG"
        curl -X POST -H 'Content-type: application/json' --data "${MSG}" "${{ inputs.slack_incoming_url }}" || {
          echo "Failed to send message to Slack"
          exit 1
        }
