name: slack-notification-main

inputs:
  status:
    required: false
    default: "failure"
  slack_incoming_url:
    required: true
  github_token:
    required: true

runs:
  using: "composite"

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch the most recent tag
      id: get_latest_tag
      shell: bash
      run: |
        echo "Fetching the most recent tag..."
        LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "Latest tag: ${LATEST_TAG}"
        echo "::set-output name=LATEST_TAG::${LATEST_TAG}"

    - name: Send slack
      shell: bash
      env:
        LATEST_TAG: ${{ steps.get_latest_tag.outputs.LATEST_TAG }}
      run: |
        echo "Running Slack notification script..."
        echo "GITHUB_REF: ${GITHUB_REF}"
        echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
        echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
        echo "LATEST_TAG: ${LATEST_TAG}"

        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          echo "Detected main branch push"
          EMOTICON="✅"
          MSG="{ \"text\":\"${EMOTICON} \`main\` branch has been pushed by \`${GITHUB_ACTOR}\`. The latest tag is \`${LATEST_TAG}\`. <https://github.com/SENSE-IM/sense-turbo/releases|View Release Notes>\" }"
        else
          echo "Deployment failed for an unknown reason"
          EMOTICON="⛔"
          MSG="{ \"text\":\"${EMOTICON} Deployment failed for \`${GITHUB_REF_NAME}\` branch pushed by \`${GITHUB_ACTOR}\`.\" }"
        fi

        curl -X POST -H 'Content-type: application/json' --data "${MSG}" "${{ inputs.slack_incoming_url }}" -v --fail || {
          echo "Failed to send message to Slack"
          exit 1
        }
