name: Generate Changelog
on:
  workflow_run:
    workflows: ["Tag Versioning"]
    types: [completed]
      
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 