name: Slack Notification for dev branch push

on:
  push:
    branches:
      - dev

jobs:
  send-slack-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set push information
        id: set_push_info
        run: |
          echo "PUSH_AUTHOR=${{ github.actor }}" >> $GITHUB_ENV
          echo "PR_URL=https://github.com/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.sha }}" >> $GITHUB_ENV

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ secrets.SLACK_DEPLOY_CHANNEL_ID }}
          payload: |
            {
              "text": "${{ env.PUSH_AUTHOR }} 가 dev 브랜치에 코드를 푸시했습니다.",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "dev 브랜치 버전이 변경되었습니다. 작업분을 merge/pull 후 진행해주세요.\n\n*푸시한 사람:* ${{ env.PUSH_AUTHOR }}\n*PR 링크:* <${{ env.PR_URL }}>"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "PR 보기"
                      },
                      "url": "${{ env.PR_URL }}",
                      "value": "view_pr"
                    }
                  ]
                }
              ]
            }
