name: Slack Notification

on:
  push:
    branches:
      - dev
      
jobs:
  send-slack-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Send Slack Notification
        uses: ./.github/actions/dev-push
        with:
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
