name: Tag Versioning

on:
  push:
    branches:
      - main

jobs:
  tag-versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current version
        id: get_version
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          echo "Current version: $CURRENT_VERSION"
          echo "::set-output name=current_version::$CURRENT_VERSION"

      - name: Create a new commit with the bumped version
        run: |
          git config --global user.name 'jayden-runners'
          git config --global user.email 'jayden@runners.im'
          NEW_VERSION=${{ steps.bump_version.outputs.new_version }}
          echo "Bumping version to $NEW_VERSION"
          jq ".version = \"$NEW_VERSION\"" package.json > package.tmp.json && mv package.tmp.json package.json
          git add package.json
          git commit -m "Bump version to $NEW_VERSION"
          git push origin main

      - name: Create a new tag
        run: |
          NEW_VERSION=${{ steps.bump_version.outputs.new_version }}
          git tag "v$NEW_VERSION"
          git push origin "v$NEW_VERSION"
